root: true
extends:
  - plugin:markdown/recommended
plugins:
  - markdown
overrides:
  - files: '**/*.md'
    processor: 'markdown/markdown'
rules:
  brace-style:
    - error
    - 1tbs
    - allowSingleLine: true
  comma-dangle: error
  comma-style:
    - error
    - last
  eol-last: error
  indent:
    - off
    - 2
    - SwitchCase: 1
  # no-multi-spaces: error
  no-param-reassign: error
  # no-trailing-spaces: error
  no-unused-vars:
    - error
    - vars: all
      args: none
      ignoreRestSiblings: true
  # no-useless-escape:
  object-curly-spacing:
    - error
    - always
  padded-blocks:
    - error
    - blocks: never
      switches: never
      classes: never
  quotes:
    - error
    - single
    - avoidEscape: true
      allowTemplateLiterals: false
